version: '3.9'

services:
  base:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    image: python-base
    volumes:
      - .:/home/python-base/project
    environment:
      PYTHONPATH: /home/python-base/project/src
    networks:
      - default
  neo4j:
    build:
      context: .
      dockerfile: docker/neo4j/Dockerfile
    networks:
      - default
    volumes:
      - ./foodmart-import.cyp:/var/lib/neo4j/foodmart-import.cyp
    environment:
      NEO4J_AUTH: none
    ports:
      - "7474:7474"
      - "7687:7687"